FROM nginx:alpine

RUN apk add --no-cache curl

# Удаляем дефолтную конфигурацию
RUN rm /etc/nginx/conf.d/default.conf

# Копируем конфигурацию для dev
COPY docker/nginx/nginx.dev.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
